/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.Chi_tiet_hd;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author Huu Danh
 */
public class XuatHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form XuatHoaDon
     */
    public static ArrayList<Chi_tiet_hd> cthds = new ArrayList<>();

    public XuatHoaDon(ArrayList<Chi_tiet_hd> data) {
        initComponents();
        DecimalFormat decimalFormat = new DecimalFormat("#,### VND");

        StringBuilder sb = new StringBuilder();
        sb.append("                                                                Trung tâm thư viện\n");
        sb.append("                                                                140/Le Trong Tan\n");
        sb.append("----------------------------------------------------------------------------------------------------------------------------------------\n");
        sb.append("                                                          HÓA ĐƠN THANH TOÁN\n");
        sb.append("Mã hóa đơn: " + data.get(0).getHoaDon().getMaHD() + "\n");
        sb.append("----------------------------------------------------------------------------------------------------------------------------------------\n");
        sb.append(String.format("%-34s %-15s %-31s %-35s\n", "Tên sách", "Số lượng", "Giá", "Tổng tiền"));
        sb.append("----------------------------------------------------------------------------------------------------------------------------------------\n");
        double TinhTongThanhTien = 0;
        for (Chi_tiet_hd cthd : data) {
            String tenSach = cthd.getSach().getTenSach();
            // Giới hạn độ dài của tên sách nếu quá dài
            TinhTongThanhTien += (cthd.getSoLuong() * cthd.getSach().getGia());
            String strSoLuong = String.valueOf(cthd.getSoLuong());
            String strGia = decimalFormat.format(cthd.getSach().getGia());
            String strTongTien = decimalFormat.format(cthd.getSoLuong() * cthd.getSach().getGia());
            
            // Sử dụng độ rộng cố định cho mỗi cột để căn chỉnh
            sb.append(String.format("%-34s %-15s %-25s %-35s\n", tenSach, strSoLuong, strGia, strTongTien));
        }
        sb.append("----------------------------------------------------------------------------------------------------------------------------------------\n");
        String strTTT = decimalFormat.format(TinhTongThanhTien);
        sb.append("Tổng thành tiền: " + strTTT);
        this.HD.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HD = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(HD);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Đóng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XuatHoaDon(cthds).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane HD;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
